kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git clone --depth 1 https://github.com/xunchangguo/rancher.git github.com/rancher/rancher
      - git checkout $DRONE_COMMIT

  - name: build
    image: rancher/dapper:1.11.2
    commands:
      - dapper ci
    when:
      branch: [master, release/*, alpha]
      event: [push,tag]

  - name: stage-binaries
    image: rancher/dapper:1.11.2
    commands:
      - cp -r ./bin/* ./package/
    when:
      branch: [master, release/*, alpha]
      event: [push,tag]

  - name: github_binary_release
    image: plugins/github-release
    settings:
      files:
        - bin/rancher-*
      checksum:
        - sha256
      api_key:
        from_secret: git_release
    when:
      branch: [master, release/*]
      event: tag
      ref:
        exclude: [ refs/tags/*rc*, refs/tags/*alpha* ]

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      repo: xunchangguo/rancher
      context: package/
      tag: ${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
    when:
      branch: [master, release/*, alpha]
      event: tag

  - name: docker-publish-agent
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile.agent
      repo: xunchangguo/rancher-agent
      context: package/
      tag: ${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
    when:
      branch: [master, release/*, alpha]
      event: tag

