#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

if [ -n "$DRONE_TAG" ]; then
    TAG=$DRONE_TAG
fi

cp ../bin/rancher ../bin/agent .

IMAGE=${REPO}/rancher:${TAG}
AGENT_IMAGE=${REPO}/rancher-agent:${TAG}
docker build --build-arg VERSION=${TAG} -t ${IMAGE} .
docker build --build-arg VERSION=${TAG} -t ${AGENT_IMAGE} -f Dockerfile.agent .
echo Built ${IMAGE} #${AGENT_IMAGE}
echo
docker save IMAGE | gzip -c > ../bin/rancher_${TAG}.tar
docker save AGENT_IMAGE | gzip -c > ../bin/release/rancher-agent_${TAG}.tar

cd ../bin
#go run ../pkg/image/export/main.go $IMAGE $AGENT_IMAGE
